apiVersion: v2
appVersion: 1.0.21
description: A platform for developing guided interviews and expert systems
name: docassemble
version: 1.0.21
dependencies:
  - name: nginx-ingress
    version: 1.40.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: inClusterNGINX,createInClusterNGINX
  - name: minio
    version: 5.0.30
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: inClusterMinio
  - name: rabbitmq
    version: 7.4.7
    repository: https://charts.bitnami.com/bitnami
    condition: inClusterRabbitMQ
