multiNodeDeployment: true
replicas: 2
postgresImage: postgres:11.9
bashImage: bash:5.1
redisImage: redis:latest
busyboxImage: busybox:1.33
timeZone: America/New_York
#locale: en_US.UTF-8 UTF-8
daImage: jhpyle/docassemble:latest
daImagePullPolicy: Always
daMonitorImage: jhpyle/docassemble-monitor:latest
daHostname: localhost
postgresStorage: 5Gi
redisStorage: 5Gi
maxBodySize: 16m
usingSslTermination: true
redirectHttp: true
exposeWebsockets: true
inClusterNGINX: true
createInClusterNGINX: true
resources:
  backend:
    requests:
      memory: "4Gi"
      cpu: "1"
    limits:
      memory: "6Gi"
      cpu: "4"
  deployment:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "6Gi"
      cpu: "8"
  postgres:
    requests:
      memory: "3Gi"
      cpu: "200m"
    limits:
      memory: "4Gi"
      cpu: "1"
  redis:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "4"
  monitor:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "500m"
#inClusterNGINXClusterIssuer: null
inClusterMinio: true
inClusterPostgres: true
inClusterRedis: true
inClusterRabbitMQ: true
s3:
  enable: false
  #bucket: null
  #accessKey: null
  #secretKey: null
azure:
  enable: false
  #accountName: null
  #accountKey: null
  #container: null
#amqpURL: null
#redisURL: null
db:
  #host: null
  exposeInternal: false
  name: docassemble
  user: docassemble
  password: abc123
  backup: false
  #port: 5432
  #tablePrefix: null
  #prefix: postgresql+psycopg2://
rabbitmq:
  auth:
    password: abc123
    erlangCookie: jmvk83gy7gsbf9kb37gk99hdf2d4jdz
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 2Gi
minio:
  persistence:
    subPath: minio
    size: 10Gi
  mode: distributed
  accessKey: "AKIAIOSFODNN7"
  secretKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCY"
  replicas: 4
  defaultBucket:
    enabled: false
    name: docassemble-bucket
  resources:
    requests:
      memory: 4Gi
    limits:
      memory: 4Gi
nginx-ingress:
  rbac.create: true
  controller:
    replicaCount: 2
    nodeSelector:
      beta.kubernetes.io/os: linux
    publishService:
      enabled: true
    config:
      use-forwarded-headers: "true"
    service:
      enableHttps: false
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi
  defaultBackend:
    nodeSelector:
      beta.kubernetes.io/os: linux
    resources:
      limits:
        cpu: 10m
        memory: 20Mi
      requests:
        cpu: 10m
        memory: 20Mi
# global:
#   storageClass: null
