apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-docassemble-backend
  labels:
    app: {{ .Release.Name }}-docassemble-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-docassemble-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-docassemble-backend
        appType: docassemble
    spec:
      {{- if .Values.multiNodeDeployment }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: appType
                operator: In
                values:
                - docassemble
            topologyKey: kubernetes.io/hostname
      {{- end }}
{{- if or .Values.inClusterMinio .Values.inClusterPostgres .Values.inClusterRedis (and .Values.adminEmail .Values.adminPassword) }}
      initContainers:
  {{- if .Values.inClusterMinio }}
      - name: init-minio
        image: {{ .Values.minio.mcImage.repository }}:{{ .Values.minio.mcImage.tag }}
        command: ['sh', '-c', 'until { mc config host add minio "$S3_ENDPOINT_URL" "$S3_ACCESS_KEY" "$S3_SECRET_KEY"; } do echo "waiting for minio"; sleep 10; done;']
        env:
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-minio-creds-secret
              key: accesskey
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-minio-creds-secret
              key: secretkey
        - name: S3_ENDPOINT_URL
          value: "http://{{ .Release.Name }}-minio:9000"
        - name: S3_BUCKET
          value: "{{ .Values.minio.defaultBucket.name }}"
  {{- end }}
  {{- if and .Values.adminEmail .Values.adminPassword }}
      - name: init-credentials
        image: {{ .Values.bashImage }}
        command: ['bash', '-c', 'echo -e "export DA_ADMIN_EMAIL=$DA_ADMIN_EMAIL\nexport DA_ADMIN_PASSWORD=$DA_ADMIN_PASSWORD" > /configdata/initial_credentials']
        volumeMounts:
        - name: config-data
          mountPath: /configdata
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-docassemble-admin-secret
  {{- end }}
  {{- if .Values.inClusterPostgres }}
      - name: init-postgres
        image: {{ .Values.postgresImage }}
        command: ['sh', '-c', 'until pg_isready -h {{ .Release.Name }}-postgres-service -p 5432; do echo waiting for postgres; sleep 2; done;']
  {{- end }}
  {{- if .Values.inClusterRedis }}
      - name: init-redis
        image: {{ .Values.redisImage }}
        command: ['sh', '-c', 'until redis-cli -h {{ .Release.Name }}-redis-service ping; do echo waiting for redis; sleep 2; done;']
  {{- end }}
{{- end }}
      containers:
      - name: docassemble
        image: {{ .Values.daImage }}
        imagePullPolicy: Always
        volumeMounts:
        - name: config-data
          mountPath: /configdata
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-docassemble-secret
        env:
        - name: CONTAINERROLE
          value: "{{ if and (not .Values.inClusterRabbitMQ) (not .Values.amqpURL) }}rabbitmq:{{ end }}{{ if and (not .Values.inClusterRabbitMQ) (not .Values.redisURL) }}redis:{{ end }}{{ if and (not .Values.inClusterPostgres) (not .Values.db.host) }}sql:{{ end }}log:cron:mail"
        {{ include "docassemble.commonEnvironment" . }}
        ports:
        - containerPort: 8082
        - containerPort: 9001
        - containerPort: 514
        - containerPort: 25
{{- if and (not .Values.inClusterRedis) (not .Values.redisURL) }}
        - containerPort: 6379
{{- end }}
{{- if and (not .Values.inClusterPostgres) (not .Values.db.host) }}
        - containerPort: 5432
{{- end }}
{{- if and (not .Values.inClusterRabbitMQ) (not .Values.amqpURL) }}
        - containerPort: 4369
        - containerPort: 5671
        - containerPort: 5672
        - containerPort: 25672
{{- end }}
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - "-c"
              - "supervisorctl status cron | grep RUNNING"
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 25
        livenessProbe:
          httpGet:
            path: /listlog/health_check
            port: 8082
          initialDelaySeconds: 1560
          periodSeconds: 60
        resources:
          requests:
            memory: "{{ .Values.resources.backend.requests.memory }}"
            cpu: "{{ .Values.resources.backend.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.backend.limits.memory }}"
            cpu: "{{ .Values.resources.backend.limits.cpu }}"
      volumes:
      - name: config-data
        emptyDir: {}
      terminationGracePeriodSeconds: 120
