apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-docassemble
  labels:
    app: {{ .Release.Name }}-docassemble
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-docassemble
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-docassemble
        appType: docassemble
    spec:
      {{- if .Values.multiNodeDeployment }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: appType
                operator: In
                values:
                - docassemble
            topologyKey: kubernetes.io/hostname
      {{- end }}
      initContainers:
      - name: init-backend
        image: {{ .Values.busyboxImage }}
        command: ['sh', '-c', 'until wget -q -O /dev/null http://{{ .Release.Name }}-docassemble-backend-service:8082/listlog/health_check?ready=1; do echo waiting for backend; sleep 2; done;']
      containers:
      - name: docassemble
        image: {{ .Values.daImage }}
        imagePullPolicy: {{ .Values.daImagePullPolicy }}
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-docassemble-secret
        env:
        - name: CONTAINERROLE
          value: "web:celery"
        {{ include "docassemble.commonEnvironment" . }}
        ports:
        - containerPort: 80
{{- if .Values.exposeWebsockets }}
        - containerPort: 5000
{{- end }}
        - containerPort: 9001
{{- if and .Values.usingSslTermination (not .Values.useAlb) .Values.redirectHttp }}
        - containerPort: 8081
{{- end }}
        readinessProbe:
          httpGet:
            path: /health_check?ready=1
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 25
        livenessProbe:
          httpGet:
            path: /health_check
            port: 80
          initialDelaySeconds: 1560
          periodSeconds: 60
        resources:
          requests:
            memory: "{{ .Values.resources.deployment.requests.memory }}"
            cpu: "{{ .Values.resources.deployment.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.deployment.limits.memory }}"
            cpu: "{{ .Values.resources.deployment.limits.cpu }}"
      terminationGracePeriodSeconds: 120
