apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-docassemble-secret
  labels:
    app: {{ .Release.Name }}-docassemble
type: Opaque
data:
  {{- if .Values.inClusterPostgres }}
  DBPASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else }}
  DBPASSWORD: {{ .Values.db.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.inClusterRabbitMQ }}
  RABBITMQ: {{ printf "pyamqp://user:%s@%s-rabbitmq//" .Values.rabbitmq.auth.password .Release.Name | b64enc | quote }}
  {{- else if .Values.amqpURL }}
  RABBITMQ: {{ .Values.amqpURL | b64enc | quote }}
  {{- end }}
  {{- if .Values.inClusterRedis }}
  REDIS: {{ include "docassemble.redisUrl" . | b64enc | quote }}
  {{- else if .Values.redisURL }}
  REDIS: {{ .Values.redisURL | b64enc | quote }}
  {{- end }}
  {{- if .Values.inClusterMinio }}
  {{- else if .Values.s3.enable }}
    {{- if .Values.s3.accessKey }}
  S3ACCESSKEY: {{ .Values.s3.accessKey | b64enc | quote }}
    {{- end }}
    {{- if .Values.s3.secretKey }}
  S3SECRETACCESSKEY: {{ .Values.s3.secretKey | b64enc | quote }}
    {{- end }}
  {{- else if .Values.azure.enable }}
  AZUREACCOUNTKEY: {{ .Values.azure.accountKey | b64enc | quote }}
  {{- end }}
  DASUPERVISORPASSWORD: {{ .Values.supervisor.password | b64enc | quote }}
  DADEFAULTSECRET: {{ .Values.secretKey | b64enc | quote }}
