{{- if .Values.inClusterNGINX }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-docassemble-ingress
  annotations:
    nginx.ingress.kubernetes.io/client-max-body-size: "{{ .Values.maxBodySize }}"
    nginx.ingress.kubernetes.io/proxy-body-size: "{{ .Values.maxBodySize }}"
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- if .Values.inClusterNGINXClusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.inClusterNGINXClusterIssuer }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.daHostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-docassemble-service
            port:
              number: 80
  {{- if .Values.inClusterNGINXClusterIssuer }}
  tls:
    - hosts:
        - {{ .Values.daHostname }}
      secretName: {{ .Release.Name }}-docassemble-ingress-certificate-secret
  {{- end }}
{{- end }}
