{{- if and .Values.inClusterNGINX .Values.exposeWebsockets }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-docassemble-ingress-sticky
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-max-body-size: "{{ .Values.maxBodySize }}"
    nginx.ingress.kubernetes.io/proxy-body-size: "{{ .Values.maxBodySize }}"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/websocket-services: "{{ .Release.Name }}-docassemble-service"
    nginx.ingress.kubernetes.io/session-cookie-path: "/"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1440m"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1440m"
    {{- if .Values.inClusterNGINXClusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.inClusterNGINXClusterIssuer }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.daHostname }}
    http:
      paths:
      - path: /ws(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-docassemble-service
            port:
              number: 5000
  {{- if .Values.inClusterNGINXClusterIssuer }}
  tls:
    - hosts:
      - {{ .Values.daHostname }}
      secretName: {{ .Release.Name }}-docassemble-ingress-certificate-secret
  {{- end }}
{{- end }}
