{{- if and .Values.adminEmail .Values.adminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-docassemble-admin-secret
  labels:
    app: {{ .Release.Name }}-docassemble
type: Opaque
data:
  DA_ADMIN_EMAIL: {{ .Values.adminEmail | b64enc | quote }}
  DA_ADMIN_PASSWORD: {{ .Values.adminPassword | b64enc | quote }}
{{- if .Values.adminApiKey }}
  DA_ADMIN_API_KEY: {{ .Values.adminApiKey | b64enc | quote }}
{{- else }}
  DA_ADMIN_API_KEY: {{ "" | b64enc | quote }}
{{- end }}
{{- end }}
