{{- if .Values.inClusterGotenberg }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gotenberg-service
spec:
  selector:
    app: {{ .Release.Name }}-gotenberg
  ports:
    - port: 3000
      targetPort: 3000
      name: http
      protocol: TCP
  type: LoadBalancer
{{- end }}
