{{- if .Values.inClusterMinio }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-creds-secret
type: Opaque
data:
  accesskey: {{ .Values.minio.auth.rootUser | b64enc | quote }}
  secretkey: {{ .Values.minio.auth.rootPassword | b64enc | quote }}
{{- end }}
