apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-docassemble-service
spec:
  selector:
    app: {{ .Release.Name }}-docassemble
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
{{- if and (or .Values.useHttps .Values.usingSslTermination) (not .Values.useAlb) .Values.redirectHttp }}
    - port: 8081
      targetPort: 8081
      name: httpredirect
      protocol: TCP
{{- end }}
{{- if .Values.exposeWebsockets }}
    - port: 5000
      targetPort: 5000
      name: wshttp
      protocol: TCP
{{- end }}
{{- if and (not .Values.useAlb) (or (not .Values.inClusterNGINX) .Values.redirectHttp .Values.webAppServiceType) }}
{{- if .Values.webAppServiceType }}
  type: {{ .Values.webAppServiceType }}
{{- else }}
  type: LoadBalancer
{{- end }}
{{- end }}
